# Generated by Django 3.0.5 on 2020-05-02 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('PatientID', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=50)),
                ('Extention', models.CharField(blank=True, max_length=5, null=True)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female'), ('A', 'Ambiguous')], max_length=1)),
                ('StreetAdd', models.CharField(max_length=255)),
                ('BrgyAdd', models.CharField(max_length=255)),
                ('CityAdd', models.CharField(max_length=255)),
                ('Region', models.CharField(choices=[('NCR', 'NCR'), ('I', 'Region I'), ('CAR', 'CAR'), ('II', 'Region II'), ('III', 'Region III'), ('IV-A', 'Region IV-A or CALABARZON'), ('MIMAROPA', 'MIMAROPA Region'), ('V', 'Region V'), ('VI', 'Region VI'), ('VII', 'Region VII'), ('VIII', 'Region VIII'), ('IX', 'Region IX)'), ('X', 'Region X'), ('XI', 'Region XI'), ('XII', 'Region XII'), ('XIII', 'Region XIII'), ('BARMM', 'BARMM')], max_length=8)),
                ('ContactPerson', models.CharField(max_length=50)),
                ('ContactNumber', models.CharField(max_length=20)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('CreatedBy', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
