# Generated by Django 3.0.5 on 2020-05-02 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Extention',
            new_name='Suffix',
        ),
    ]
