# Generated by Django 3.0.5 on 2020-05-25 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20200512_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='ContactNumber',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ContactPerson',
        ),
        migrations.AddField(
            model_name='patient',
            name='CaseNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='POB',
            field=models.CharField(default='blank', max_length=75),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ContactData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MothersName', models.CharField(blank=True, max_length=75, null=True)),
                ('MAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('MContactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('FathersName', models.CharField(blank=True, max_length=75, null=True)),
                ('FAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('FContactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('AltContactName', models.CharField(blank=True, max_length=75, null=True)),
                ('AltAddress', models.CharField(blank=True, max_length=255, null=True)),
                ('AltContactNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GestationAge', models.IntegerField()),
                ('BirthWeight', models.IntegerField()),
                ('BirthHospital', models.CharField(max_length=100)),
                ('CollectionHospital', models.CharField(max_length=100)),
                ('AttendingPhys', models.CharField(max_length=50)),
                ('AttendingContact', models.CharField(max_length=20)),
                ('SpecialistName', models.CharField(max_length=50)),
                ('SpecialistContact', models.CharField(max_length=20)),
                ('CollectionDate', models.DateTimeField()),
                ('SampleReceptionDate', models.DateTimeField()),
                ('RCollectionDate', models.DateTimeField()),
                ('RSampleReceptionDate', models.DateTimeField()),
                ('Diagnosis', models.CharField(max_length=100)),
                ('DiagnosisDate', models.DateTimeField()),
                ('TreatmentDate', models.DateTimeField()),
                ('Note', models.CharField(max_length=255)),
                ('PatientID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical', to='patients.Patient')),
            ],
        ),
    ]
