# Generated by Django 3.0.5 on 2020-05-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200525_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClinicalData',
            new_name='PatientClinical',
        ),
        migrations.RenameModel(
            old_name='ContactData',
            new_name='PatientContact',
        ),
    ]
