# Generated by Django 3.0.5 on 2020-05-30 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20200530_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinical',
            name='patientID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='clinical', to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='patientID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='patients.Patient'),
        ),
    ]
