# Generated by Django 3.0.5 on 2020-05-30 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20200530_1317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientclinical',
            old_name='patientID',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='patientcontact',
            old_name='patientID',
            new_name='patient',
        ),
    ]
