# Generated by Django 3.0.5 on 2020-06-13 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0015_auto_20200607_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinical',
            name='rCollectionDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='rSampleReceptionDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
