# Generated by Django 3.0.5 on 2020-07-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0019_auto_20200706_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinical',
            name='patientType',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
