# Generated by Django 3.0.5 on 2020-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0020_patientclinical_patienttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
