# Generated by Django 3.0.5 on 2020-07-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0021_auto_20200706_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinical',
            name='status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
