# Generated by Django 3.0.5 on 2020-07-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_remove_schedules_patient'),
        ('patients', '0025_auto_20200726_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientclinical',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientcontact',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
