# Generated by Django 3.0.5 on 2020-07-26 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0026_auto_20200726_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('middleName', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('sex', models.CharField(choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female'), ('A', 'Ambiguous')], max_length=1)),
                ('DOB', models.DateField()),
                ('POB', models.CharField(max_length=75)),
                ('streetAdd', models.CharField(max_length=255)),
                ('brgyAdd', models.CharField(max_length=255)),
                ('cityAdd', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('NCR', 'NCR'), ('I', 'Region I'), ('CAR', 'CAR'), ('II', 'Region II'), ('III', 'Region III'), ('IV-A', 'Region IV-A or CALABARZON'), ('MIMAROPA', 'MIMAROPA Region'), ('V', 'Region V'), ('VI', 'Region VI'), ('VII', 'Region VII'), ('VIII', 'Region VIII'), ('IX', 'Region IX)'), ('X', 'Region X'), ('XI', 'Region XI'), ('XII', 'Region XII'), ('XIII', 'Region XIII'), ('BARMM', 'BARMM')], max_length=8)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('createdBy', models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='patient',
            field=models.OneToOneField(default='CLNGN', on_delete=django.db.models.deletion.CASCADE, related_name='clinical', to='patients.Patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientcontact',
            name='patient',
            field=models.OneToOneField(default='CLNGN', on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='patients.Patient'),
            preserve_default=False,
        ),
    ]
