# Generated by Django 3.0.5 on 2020-07-26 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0027_auto_20200726_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientclinical',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientcontact',
            name='patient',
        ),
        migrations.DeleteModel(
            name='Patient',
        ),
        migrations.DeleteModel(
            name='PatientClinical',
        ),
        migrations.DeleteModel(
            name='PatientContact',
        ),
    ]
