# Generated by Django 3.0.5 on 2020-07-26 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0028_auto_20200726_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('suffix', models.CharField(blank=True, max_length=5, null=True)),
                ('sex', models.CharField(choices=[('', 'Choose...'), ('M', 'Male'), ('F', 'Female'), ('A', 'Ambiguous')], max_length=1)),
                ('dob', models.DateField()),
                ('pob', models.CharField(max_length=75)),
                ('street_add', models.CharField(max_length=255)),
                ('brgy_add', models.CharField(max_length=255)),
                ('city_add', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('NCR', 'NCR'), ('I', 'Region I'), ('CAR', 'CAR'), ('II', 'Region II'), ('III', 'Region III'), ('IV-A', 'Region IV-A or CALABARZON'), ('MIMAROPA', 'MIMAROPA Region'), ('V', 'Region V'), ('VI', 'Region VI'), ('VII', 'Region VII'), ('VIII', 'Region VIII'), ('IX', 'Region IX)'), ('X', 'Region X'), ('XI', 'Region XI'), ('XII', 'Region XII'), ('XIII', 'Region XIII'), ('BARMM', 'BARMM')], max_length=8)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothers_name', models.CharField(blank=True, max_length=75)),
                ('mAddress', models.CharField(blank=True, max_length=255)),
                ('mContact_number', models.CharField(blank=True, max_length=20)),
                ('fathers_name', models.CharField(blank=True, max_length=75)),
                ('faddress', models.CharField(blank=True, max_length=255)),
                ('fcontactNumber', models.CharField(blank=True, max_length=20)),
                ('altcontact_ame', models.CharField(blank=True, max_length=75)),
                ('alt_address', models.CharField(blank=True, max_length=255)),
                ('altcontact_number', models.CharField(blank=True, max_length=20)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='patients.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=30, null=True)),
                ('patient_nype', models.CharField(blank=True, max_length=3)),
                ('referring_doctor', models.CharField(blank=True, max_length=75)),
                ('referring_service', models.CharField(blank=True, max_length=75)),
                ('referral_reason', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(blank=True, max_length=10)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinical', to='patients.Patient')),
            ],
        ),
    ]
