# Generated by Django 3.0.7 on 2020-08-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0030_auto_20200806_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_id',
            new_name='patient_i_d',
        ),
    ]
