# Generated by Django 3.0.5 on 2021-02-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0033_auto_20210212_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinical',
            name='patient_type',
            field=models.CharField(blank=True, max_length=14),
        ),
    ]
