# Generated by Django 3.0.5 on 2021-03-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0036_auto_20210218_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinical',
            name='case_number',
            field=models.CharField(blank=True, default='', max_length=30),
            preserve_default=False,
        ),
    ]
