# Generated by Django 3.0.7 on 2020-08-08 08:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_auto_20200808_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='UserPermissions',
        ),
    ]
