# Generated by Django 3.0.7 on 2020-08-08 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissions',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
