# Generated by Django 3.0.5 on 2020-07-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0007_remove_schedules_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedulestaff',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedulestaff',
            name='staff',
        ),
        migrations.DeleteModel(
            name='Schedules',
        ),
        migrations.DeleteModel(
            name='ScheduleStaff',
        ),
    ]
