# Generated by Django 3.0.7 on 2020-08-08 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0009_schedules_schedulestaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PatientClinicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('status', models.CharField(max_length=2)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_schedule', to='schedules.ClinicSchedule')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=75)),
                ('event_type', models.CharField(max_length=75)),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('description', models.TextField(max_length=225)),
                ('attendees', models.ManyToManyField(related_name='attendees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='schedules.Events'),
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='physician',
            field=models.ManyToManyField(related_name='attending_physician', to=settings.AUTH_USER_MODEL),
        ),
    ]
