# Generated by Django 3.0.5 on 2020-08-13 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0020_auto_20200811_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='patientclinicschedule',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
