# Generated by Django 3.0.7 on 2020-08-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0024_auto_20200830_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicschedulepatient',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='clinicschedulepatient',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='clinicschedulepatient',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='ClinicSchedule',
        ),
        migrations.DeleteModel(
            name='ClinicSchedulePatient',
        ),
    ]
