# Generated by Django 3.0.7 on 2020-08-30 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0032_auto_20200806_1146'),
        ('schedules', '0025_auto_20200830_1449'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='schedules.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicSchedulePatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('status', models.CharField(max_length=15)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_patient', to='patients.Patient')),
                ('physician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atttending_physician', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='schedules.ClinicSchedule')),
            ],
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='physician',
            field=models.ManyToManyField(related_name='attending_physician', through='schedules.ClinicSchedulePatient', to=settings.AUTH_USER_MODEL),
        ),
    ]
