# Generated by Django 3.0.7 on 2020-08-31 01:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0026_auto_20200830_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicschedulepatient',
            name='physician',
        ),
        migrations.RemoveField(
            model_name='clinicschedule',
            name='physician',
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='physician',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='attending_physician', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
