# Generated by Django 3.0.5 on 2020-09-05 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0030_auto_20200905_1211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='end_time',
            new_name='time_end',
        ),
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='start_time',
            new_name='time_start',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='time_start',
            new_name='start_time',
        ),
    ]
