# Generated by Django 3.0.5 on 2020-09-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0031_auto_20200905_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinicschedulepatient',
            name='appointment_type',
            field=models.CharField(default='New', max_length=5),
            preserve_default=False,
        ),
    ]
