# Generated by Django 3.0.5 on 2020-05-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20200525_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinical',
            name='Status',
            field=models.CharField(default='Active', max_length=10),
            preserve_default=False,
        ),
    ]
