# Generated by Django 3.0.5 on 2020-05-30 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0010_auto_20200530_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientclinical',
            name='collectionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='diagnosisDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical', to='patients.Patient'),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='rCollectionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='rSampleReceptionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='sampleReceptionDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='treatmentDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='patientcontact',
            name='patientID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contact', to='patients.Patient'),
        ),
    ]
