# Generated by Django 3.0.5 on 2020-07-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0016_auto_20200613_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientclinical',
            name='attendingContact',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='attendingPhys',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='birthHospital',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='birthWeight',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='collectionDate',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='collectionHospital',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='diagnosisDate',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='gestationAge',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='note',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='rCollectionDate',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='rSampleReceptionDate',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='sampleReceptionDate',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='specialistContact',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='specialistName',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='status',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='treatmentDate',
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='caseNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='finalDiagnosis',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='medicalHistory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='otherHistory',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='referralReason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='referringDoctor',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='referringService',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='patientclinical',
            name='workingImpression',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
