# Generated by Django 3.0.5 on 2020-07-06 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0017_auto_20200702_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='caseNumber',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='finalDiagnosis',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='medicalHistory',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='otherHistory',
        ),
        migrations.RemoveField(
            model_name='patientclinical',
            name='workingImpression',
        ),
    ]
