# Generated by Django 3.0.5 on 2020-07-09 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0022_patientclinical_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='middleName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientclinical',
            name='caseNumber',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
