# Generated by Django 3.0.5 on 2020-07-26 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0023_auto_20200709_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patientID',
            new_name='ace',
        ),
    ]
