# Generated by Django 3.0.5 on 2020-07-26 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0024_auto_20200726_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ace',
            new_name='patientID',
        ),
    ]
