# Generated by Django 3.0.7 on 2020-08-06 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0031_auto_20200806_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_i_d',
            new_name='patient_id',
        ),
    ]
