# Generated by Django 3.0.5 on 2020-07-25 02:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0023_auto_20200709_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('timeStart', models.TimeField()),
                ('timeEnd', models.TimeField()),
                ('location', models.CharField(max_length=50)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='patients.Patient')),
                ('scheduledBy', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='scheduler', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleStaff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduleId', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='schedules.Schedules')),
                ('staffId', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='staff', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
