# Generated by Django 3.0.5 on 2020-07-25 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200725_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulestaff',
            name='scheduleID',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='schedules.Schedules'),
        ),
    ]
