# Generated by Django 3.0.5 on 2020-07-26 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0004_auto_20200725_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='patientID',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='schedulestaff',
            old_name='scheduleID',
            new_name='schedule',
        ),
    ]
