# Generated by Django 3.0.7 on 2020-08-08 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_auto_20200806_1146'),
        ('schedules', '0012_auto_20200808_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientclinicschedule',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_patient', to='patients.Patient'),
            preserve_default=False,
        ),
    ]
