# Generated by Django 3.0.7 on 2020-08-08 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0016_auto_20200808_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='createdBy',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clinicschedule',
            name='physician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attending_physician', to=settings.AUTH_USER_MODEL),
        ),
    ]
