# Generated by Django 3.0.5 on 2020-08-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0017_auto_20200808_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='attendees',
        ),
        migrations.RemoveField(
            model_name='event',
            name='createdBy',
        ),
        migrations.RemoveField(
            model_name='patientclinicschedule',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='patientclinicschedule',
            name='schedule',
        ),
        migrations.DeleteModel(
            name='ClinicSchedule',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='PatientClinicSchedule',
        ),
    ]
