# Generated by Django 3.0.5 on 2020-08-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0032_auto_20200806_1146'),
        ('schedules', '0021_auto_20200813_2109'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PatientClinicSchedule',
            new_name='ClinicSchedulePatient',
        ),
    ]
