# Generated by Django 3.0.5 on 2020-08-23 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schedules', '0022_auto_20200819_1943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicschedule',
            name='physician',
        ),
        migrations.AddField(
            model_name='clinicschedule',
            name='physician',
            field=models.ManyToManyField(related_name='attending_physician', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clinicschedulepatient',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='schedules.ClinicSchedule'),
        ),
    ]
