# Generated by Django 3.0.5 on 2020-09-05 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0029_auto_20200831_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='time_end',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='time_start',
            new_name='start_time',
        ),
    ]
