# Generated by Django 3.0.5 on 2020-09-19 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0032_clinicschedulepatient_appointment_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clinicschedulepatient',
            name='time_end',
        ),
        migrations.RemoveField(
            model_name='clinicschedulepatient',
            name='time_start',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_time',
        ),
    ]
