# Generated by Django 3.0.7 on 2020-09-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0034_auto_20200919_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicschedulepatient',
            name='appointment_type',
            field=models.CharField(default='none', max_length=5),
        ),
    ]
