# Generated by Django 3.0.5 on 2020-10-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0036_auto_20200920_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='time_end',
            new_name='start_end',
        ),
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='time_start',
            new_name='start_time',
        ),
    ]
