# Generated by Django 3.0.5 on 2020-10-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0037_auto_20201008_2125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinicschedulepatient',
            old_name='start_end',
            new_name='end_time',
        ),
    ]
