export const GET_PATIENT = "GET_PATIENT";
export const GET_PATIENTS = "GET_PATIENTS";
export const DELETE_PATIENT = "DELETE_PATIENT";
export const ADD_PATIENT = "ADD_PATIENT";
export const EDIT_PATIENT = "EDIT_PATIENT";
export const DISCHARGE_PATIENT = "DISCHARGE_PATIENT";
export const FILTER_PATIENT_TABLE = "FILTER_PATIENT_TABLE";
export const SEARCH_PATIENTS = "SEARCH_PATIENTS";

export const GET_EVENTS = "GET_EVENTS";
export const ADD_EVENT = "ADD_EVENTS";
export const EDIT_EVENT = "EDIT_EVENTS";
export const DELETE_EVENT = "GET_EVENTS";

export const GET_SCHEDULES = "GET_SCHEDULES";
export const CREATE_EVENTSCHEDULE = "CREATE_EVENTSCHEDULE";
export const EDIT_EVENTSCHEDULE = "EDIT_EVENTSCHEDULE";
export const DELETE_EVENTSCHEDULE = "DELETE_EVENTSCHEDULE";
export const GET_SCHEDULED_PATIENTS = "GET_SCHEDULED_PATIENTS";
export const GET_AVAILABLE_PHYSICIANS = "GET_AVAILABLE_PHYSICIANS";
export const LOAD_SCHEDULES = "LOAD_SCHEDULES";
export const GET_AVAILABLE_PATIENTS = "GET_AVAILABLE_PATIENTS";
export const CREATE_PATIENT_APPOINTMENT = "CREATE_PATIENT_APPOINTMENT";
export const GET_PATIENT_APPOINTMENT_DETAILS = "GET_PATIENT_APPOINTMENT_DETAILS";
export const EDIT_PATIENT_APPOINTMENT = "EDIT_PATIENT_APPOINTMENT";
export const DELETE_PATIENT_APPOINTMENT = "DELETE_PATIENT_APPOINTMENT";
export const NEW_DATE_SELECTED = "NEW_DATE_SELECTED";
export const SCHEDULE_SELECTED = "SCHEDULE_SELECTED";

export const SHOW_MODAL = "SHOW_MODAL";
export const HIDE_MODAL = "HIDE_MODAL";

export const LOAD_OVERLAY = "LOAD_OVERLAY";
export const UNLOAD_OVERLAY = "UNLOAD_OVERLAY";

export const GET_ERRORS = "GET_ERRORS";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
